services:
  tendrel-database:
    image: postgres:latest
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf

  tendrel-graphql:
    image: tendrel-graphql-dev
    build:
      context: .
      args:
        NODE_ENV: development
    depends_on:
      - tendrel-database
    environment:
      DATABASE_URL: postgresql://postgres:password@tendrel-database:5432/postgres
    env_file:
      - .env.local
    ports:
      - 4000:4000
    pull_policy: build

volumes:
  pgdata:
