type Query {
  """Fetches an object given its ID"""
  entity(
    """The ID of an object"""
    id: ID!
  ): Node
  entities(
    """Returns the items in the list that come after the specified cursor."""
    after: String

    """Returns the first n items from the list."""
    first: Int

    """Returns the items in the list that come before the specified cursor."""
    before: String

    """Returns the last n items from the list."""
    last: Int
  ): EntityConnection
  user: User
}

"""An object with an ID"""
interface Node {
  """The id of the object."""
  id: ID!
}

"""A connection to a list of items."""
type EntityConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [EntityEdge]
}

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

"""An edge in a connection."""
type EntityEdge {
  """The item at the end of the edge"""
  node: Entity

  """A cursor for use in pagination"""
  cursor: String!
}

type Entity implements Node {
  """The ID of an object"""
  id: ID!
  components(
    """Returns the items in the list that come after the specified cursor."""
    after: String

    """Returns the first n items from the list."""
    first: Int

    """Returns the items in the list that come before the specified cursor."""
    before: String

    """Returns the last n items from the list."""
    last: Int
  ): ComponentConnection
}

"""A connection to a list of items."""
type ComponentConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [ComponentEdge]
}

"""An edge in a connection."""
type ComponentEdge {
  """The item at the end of the edge"""
  node: Component

  """A cursor for use in pagination"""
  cursor: String!
}

union Component = ActivationState | Name

type ActivationState implements Node {
  """The ID of an object"""
  id: ID!
  isActive: Boolean!
}

type Name implements Node {
  """The ID of an object"""
  id: ID!
  name: String!
}

type User implements Node {
  """The ID of an object"""
  id: ID!
  createdAt: String!
  updatedAt: String!
  name: String!
  organizations(
    """Returns the items in the list that come after the specified cursor."""
    after: String

    """Returns the first n items from the list."""
    first: Int

    """Returns the items in the list that come before the specified cursor."""
    before: String

    """Returns the last n items from the list."""
    last: Int
  ): OrganizationConnection
}

"""A connection to a list of items."""
type OrganizationConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [OrganizationEdge]
}

"""An edge in a connection."""
type OrganizationEdge {
  """The item at the end of the edge"""
  node: Organization

  """A cursor for use in pagination"""
  cursor: String!
}

type Organization implements Node {
  """The ID of an object"""
  id: ID!
  createdAt: String!
  updatedAt: String!
  name: String!
  templates(
    """Returns the items in the list that come after the specified cursor."""
    after: String

    """Returns the first n items from the list."""
    first: Int

    """Returns the items in the list that come before the specified cursor."""
    before: String

    """Returns the last n items from the list."""
    last: Int
  ): TemplateConnection
}

"""A connection to a list of items."""
type TemplateConnection {
  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """A list of edges."""
  edges: [TemplateEdge]
}

"""An edge in a connection."""
type TemplateEdge {
  """The item at the end of the edge"""
  node: Template

  """A cursor for use in pagination"""
  cursor: String!
}

type Template implements Node {
  """The ID of an object"""
  id: ID!
  createdAt: String!
  updatedAt: String!
  name: String!
}