services:
  graphql:
    build:
      context: ..
      dockerfile: config/graphql.dockerfile
    env_file: ../.env.local
    environment:
      PGUSER: graphql
    network_mode: host
    ports:
      - 4000:4000
    restart: always
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    network_mode: host
    ports:
      - 80:80
  postgrest:
    build:
      context: ..
      dockerfile: config/postgrest.dockerfile
    env_file: ../.env.local
    environment:
      PGUSER: graphql
    network_mode: host
    ports:
      - 4001:4001
    restart: always
