name: chores

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - run: nix develop .#ci --command bun install --frozen-lockfile
      # This step performs several checks, all of which are configured through
      # flake.nix. If you are reading this because your GitHub PR workflow
      # failed, it is almost certainly due to formatting. Formatting is done
      # with `treefmt` and configured in flake.nix:
      # - alejandra: nix
      # - biome: graphql, json, typescript
      # - prettier: markdown, yaml
      # - sqlfmt: sql
      - run: nix flake check --impure .

  package:
    name: packaging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
