name: end to end tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ !github.event.pull_request.draft }}
    timeout-minutes: 30
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            accept-flake-config = true
      - uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:test
      - id: check-cache
        uses: actions/cache/restore@v4
        with:
          path: db.dump
          key: ${{ runner.os }}-db-dump-2025-03-28
      - if: steps.check-cache.outputs.cache-hit != 'true'
        run: nix develop -c just dump
        env:
          PGDATABASE: ${{ secrets.TEST_PGDATABASE }}
          PGHOST: ${{ secrets.TEST_PGHOST }}
          PGPASSWORD: ${{ secrets.TEST_PGPASSWORD }}
          PGUSER: ${{ secrets.TEST_PGUSER }}
      - if: steps.check-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: db.dump
          key: ${{ steps.check-cache.outputs.cache-primary-key }}
      - run: nix develop -c just dbname=tendrel restore
        env:
          PGDATABASE: tendrel
          PGHOST: localhost
          PGPASSWORD: postgres
          PGUSER: postgres
      - run: nix develop -c just target=ci migrate
      - run: nix develop -c just install
      # - run: nix develop -c just test # pgTAP is not installed :(
      - run: nix develop -c bun test
        env:
          BASE_URL: http://localhost:3001/api/v1
          PGDATABASE: tendrel
          PGHOST: localhost
          PGPASSWORD: postgres
          PGUSER: postgres
          X_TENDREL_USER: user_2jJ7Xl0LFewQGKKNYwfFWAM0Lmc
